### ISSUE TITLE
Truncated long fields (abstract) inaccessible as feed entry

### ISSUE THREAD

**Issue by fcheslack** [aurimasv/zotero#16]
Because the right pane is read only for feed entries, the full text of long fields that are truncated in display mode can't be read. This may only matter for abstract.

**Comment by aurimasv** [comment]
But abstracts can be expanded by clicking on the label, no?

In general, the plan is to re-design the right-hand pane to make it more attractive and useful by putting focus on the title, more compact author list, and abstract. I think this would look sort of like the abstract views of articles online.

**Comment by fcheslack** [comment]
So it is. I had no idea that was clickable (I expected a highlight or a cursor change if it was, but this seems to be the same as regular Zotero items). For a feed reading purposes, making it expanded by default might be better though.
