### ISSUE TITLE
Additional fields for Add Feeds

### ISSUE THREAD

**Issue by lmrhody** [aurimasv/zotero#23]
Sorry if I'm adding things here that are discussed elsewhere. I looked around but didn't see this, though. Would it be possible to include more information about a feed when adding it? For example, the name of the author of the feed, which may be different from the author of the post might be useful.

**Comment by aurimasv** [comment]
Where would that information be displayed (besides in the add/edit feed dialog)? Or is that the only place? The author of the feed is currently used as the author of the feed item if no author is provided specifically for a feed item.

**Comment by lmrhody** [comment]
At the item level, it would be useful to see the author of the feed/blog which may differ from the author of the post/item and also, in case one is browsing all feed items, it's valuable to see the title of the blog for each item while scrolling up and down the middle panel. I think that by default, you're absolutely right that the author of the feed should also be author of the item absent an additional author.

**Comment by aurimasv** [comment]
Continued in #26
