### ISSUE TITLE
error adding new feed

### ISSUE THREAD

**Issue by fcheslack** [aurimasv/zotero#7]
debug: https://gist.github.com/fcheslack/066958ebc98244a94258

**Comment by aurimasv** [comment]
Is this for a specific feed? Can you provide a URL?

**Comment by fcheslack** [comment]
It was just http://cyber.law.harvard.edu/rss/examples/rss2sample.xml
and it didn't leave any lasting brokenness, it just broke rendering the item list until it was restarted (and when restarted that feed had been populated)

**Comment by aurimasv** [comment]
Closed via 2e463f5
